In [2]:
pip install numpy

In [3]:
import numpy as np


In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a.ndim)

b=np.array([1, 2, 3], dtype='f')
print(b)
print(b.ndim)

c = np.zeros((2,2),dtype=np.complex_)
print(c)
print(c.ndim)


[1 2 3 4 5]
1
[1. 2. 3.]
1
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
2


In [5]:
#ADD
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2= np.array( [[7, 8, 9], [10, 11, 12]])
np.add(arr,arr2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [6]:
#TRANSPOSE
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
#DOT PRODUCT
a = [[1, 2], [4, 1]]  
b = [[4, 11], [2, 3]]  
c=np.dot(a, b)  
c  

array([[ 8, 17],
       [18, 47]])

In [ ]:
#Row coloumn access/Slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [8]:
pip install urllib3

In [9]:
import urllib.request

In [ ]:

urllib.request.urlretrieve(url = "https://figshare.com/articles/dataset/Average_Monthly_Precipitation_for_Boulder_CO_csv_/6856262",filename = "precip-months.csv")



('precip-months.csv', <http.client.HTTPMessage at 0x7f020a9cf898>)

In [ ]:
urllib.request.urlretrieve(url ="https://ndownloader.figshare.com/files/12565619",filename="months.txt")


('months.txt', <http.client.HTTPMessage at 0x7f020aa05438>)

In [ ]:

months = np.genfromtxt("months.txt", dtype='str')
print(months)

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June' 'July' 'Aug' 'Sept' 'Oct' 'Nov'
 'Dec']


In [10]:
urllib.request.urlretrieve(url ="https://ndownloader.figshare.com/files/12565619",filename="months.txt")

('months.txt', <http.client.HTTPMessage at 0x7fb229b2c400>)

In [11]:
months = np.genfromtxt("months.txt", dtype='str')
print(months)

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June' 'July' 'Aug' 'Sept' 'Oct' 'Nov'
 'Dec']
